### ISSUE TITLE
[BUG] Examples that are linked to via the README are missing.

### ISSUE THREAD

**Issue by iangregsondev** [libsv/go-bc#47] opened 2022-05-23 16:16 UTC
**Describe the bug**
The documentation examples are missing and the links in the README point to an invalid URL 

https://github.com/libsv/go-bc/blob/master/examples

**To Reproduce**
Click on the link and check the README

**Expected behavior**
Examples would be nice to be able to see how to use the library.

**Comment by sirdeggen** [comment] 2023-09-08 18:47
Not really a bug, the readme is some default placeholder. The issue is valid but closing here so we can keep fresh issues top of mind. Let's call this one "Have better docs".

**Closed by sirdeggen** 2023-09-08 18:47 UTC
Labels: bug
